### ISSUE TITLE
Support for REUSEADDR

### ISSUE THREAD

**Issue by diclophis** [cotag/libuv#6]
Hello,

Does this library support setting `REUSEADDR` flags on TCP sockets?

**Comment by stakach** [comment]
Support added in libuv (3.1.2)

```ruby
tcp = reactor.tcp(flags: REUSEADDR | SOMEOTHER_FLAG)
tcp.bind('0.0.0.0', port) do |client|
    client.progress do |data|
        client.write('pong')
    end
    client.start_read
end
```

**Comment by diclophis** [comment]
Totally awesome, thanks!

**Comment by diclophis** [comment]
Small issue... i am unable to find the resolved reference to `Libuv:: REUSEADDR` ...

**Comment by stakach** [comment]
released libuv (3.1.3)
Constants are defined here: http://www.rubydoc.info/stdlib/socket/1.9.3/Socket/Constants
Same in later versions of rubies however couldn't find the docs

**Comment by diclophis** [comment]
Am I reading this code correctly, or is it impossible actually in `libuv` source to actually change the flags?

https://github.com/libuv/libuv/blob/v1.x/src/unix/tcp.c#L63

???

**Comment by stakach** [comment]
I think it is actually impossible not to use that flag: https://github.com/libuv/libuv/blob/v1.x/src/unix/tcp.c#L107

**Comment by diclophis** [comment]
... haha yea, as it turns out i had a logic bug in my test suite that caused my issue... but thanks again for all the quick updates
